#server:
#  error:
#    whitelabel.enabled: false

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  data:
    rest:
      detection-strategy: annotated
      base-path: /api2

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

app:
  version: 1