#server:
#  error:
#    whitelabel.enabled: false

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  data:
    rest:
      detection-strategy: annotated
      base-path: /api

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8090/realms/lab4
          jwk-set-uri: http://keycloak:8090/realms/lab4/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8090/realms/lab4
            jwk-set-uri: http://keycloak:8090/realms/lab4/protocol/openid-connect/certs
        registration:
          keycloak:
            client-id: web-lab4-server
            client-secret: W6yIrCWcD0WIZTlZ0tyeCprIgIjikvfb
            scope: openid


springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /


app:
  version: 1

server:
  address: 0.0.0.0